/**
 * Career knowledge base seed (docs/PRODUCT_STRATEGY.md §6, §31).
 *
 * This is the admin-curated data the recommendation engine reasons over —
 * nothing here is AI-generated, and the engine can never recommend a
 * career, skill, or pathway that isn't a row in this file. ~24 careers,
 * chosen to span technical, business, creative, social, and hands-on
 * profiles so the scoring engine (src/lib/career-engine/scoring.ts)
 * produces genuinely different results for genuinely different people.
 *
 * Certifications named below are real, well-known credential programs
 * (Google Career Certificates, CompTIA, HubSpot, Meta Blueprint) referenced
 * generically by name — no specific URLs, which age and rot, are stored.
 * No salary or income figures appear anywhere in this file.
 */
import { PrismaClient, type SkillLevel, type WorkEnvironment } from "@prisma/client";

const prisma = new PrismaClient();

// Skills not already in the base onboarding catalog (prisma/seed.ts),
// needed specifically for career requirements. Upserted the same way —
// by unique name — so the two seed scripts share one growing catalog.
const CAREER_SKILLS: { name: string; category: string }[] = [
  { name: "Programming fundamentals", category: "Digital & Tech" },
  { name: "JavaScript", category: "Digital & Tech" },
  { name: "Database basics", category: "Digital & Tech" },
  { name: "UX research", category: "Digital & Tech" },
  { name: "Wireframing & prototyping", category: "Digital & Tech" },
  { name: "Network & hardware troubleshooting", category: "Digital & Tech" },
  { name: "SEO", category: "Digital & Tech" },
  { name: "Content strategy", category: "Communication & Language" },
  { name: "Analytics & reporting", category: "Analytical" },
  { name: "Advanced video production", category: "Creative" },
  { name: "Media relations", category: "Communication & Language" },
  { name: "Press release writing", category: "Communication & Language" },
  { name: "Financial analysis", category: "Business & Admin" },
  { name: "Payroll & compliance basics", category: "Business & Admin" },
  { name: "Recruitment & interviewing", category: "Business & Admin" },
  { name: "Budgeting", category: "Business & Admin" },
  { name: "Scheduling & planning", category: "Business & Admin" },
  { name: "Risk management", category: "Analytical" },
  { name: "Business plan development", category: "Business & Admin" },
  { name: "Pitching & fundraising basics", category: "Business & Admin" },
  { name: "Lesson planning", category: "Interpersonal & Leadership" },
  { name: "Classroom & behavior management", category: "Interpersonal & Leadership" },
  { name: "Patient care basics", category: "Interpersonal & Leadership" },
  { name: "Health & hygiene education", category: "Interpersonal & Leadership" },
  { name: "Community outreach", category: "Interpersonal & Leadership" },
  { name: "Case management basics", category: "Business & Admin" },
  { name: "Crop & soil management", category: "Analytical" },
  { name: "Farm business planning", category: "Business & Admin" },
  { name: "Technical drawing / CAD basics", category: "Digital & Tech" },
  { name: "Construction site supervision", category: "Interpersonal & Leadership" },
  { name: "Electrical wiring & safety", category: "Analytical" },
  { name: "Solar & renewable installation basics", category: "Analytical" },
  { name: "Client relationship management", category: "Business & Admin" },
];

type CareerSeed = {
  slug: string;
  name: string;
  description: string;
  industry: string;
  responsibilities: string[];
  relevantSubjects: string[];
  relevantInterests: string[];
  traitWeights: Record<string, number>;
  educationPathways: string[];
  alternativePathways: string[];
  certifications: string[];
  beginnerProjects: string[];
  portfolioRequirements: string[];
  remoteSuitable: boolean;
  freelanceSuitable: boolean;
  environments: WorkEnvironment[];
  skills: { name: string; level: SkillLevel }[];
};

const CAREERS: CareerSeed[] = [
  {
    slug: "digital-marketing",
    name: "Digital Marketing",
    description:
      "Planning and running campaigns that help a business or brand reach people online — social media, content, email, and paid ads.",
    industry: "Marketing & Communications",
    responsibilities: [
      "Plan and schedule content across social platforms",
      "Write ad copy and captions",
      "Track campaign performance and report on what's working",
      "Research audiences and competitors",
    ],
    relevantSubjects: ["English", "Literature", "Economics", "Business Studies", "Mathematics"],
    relevantInterests: ["Marketing & branding", "Business & entrepreneurship", "Media & journalism"],
    traitWeights: { creativity: 0.8, communication: 0.9, businessOrientation: 0.8, analyticalThinking: 0.5, socialOrientation: 0.4 },
    educationPathways: ["Any degree, especially Marketing, Communications, or Business"],
    alternativePathways: ["Self-taught via free courses + a portfolio of real campaigns", "Certificate programs, no degree required"],
    certifications: ["Google Digital Marketing & E-commerce Certificate", "HubSpot Content Marketing Certification", "Meta Social Media Marketing Certificate"],
    beginnerProjects: ["Create a 30-day social media content calendar for a real or fictional local business", "Write and design 5 ad concepts for a product"],
    portfolioRequirements: ["2-3 sample campaigns or content calendars", "Before/after examples if you've managed a real account"],
    remoteSuitable: true,
    freelanceSuitable: true,
    environments: ["REMOTE", "HYBRID", "IN_PERSON"],
    skills: [
      { name: "Social media platforms", level: "INTERMEDIATE" },
      { name: "Copywriting", level: "INTERMEDIATE" },
      { name: "Content strategy", level: "INTERMEDIATE" },
      { name: "SEO", level: "BEGINNER" },
      { name: "Analytics & reporting", level: "BEGINNER" },
      { name: "Canva / basic graphic design", level: "BEGINNER" },
    ],
  },
  {
    slug: "software-development",
    name: "Software Development",
    description: "Building the applications and systems that run on computers, phones, and the web.",
    industry: "Technology",
    responsibilities: [
      "Write and test code to build features",
      "Fix bugs and improve performance",
      "Work with a team to plan and review changes",
      "Keep learning new tools and languages",
    ],
    relevantSubjects: ["Mathematics", "Computer Science", "Physics"],
    relevantInterests: ["Technology & software", "Engineering & how things work"],
    traitWeights: { analyticalThinking: 0.9, problemSolving: 0.9, technologyInterest: 0.9, creativity: 0.4 },
    educationPathways: ["Computer Science or related degree"],
    alternativePathways: ["Self-taught / bootcamp with a strong project portfolio — this field hires on demonstrated skill more than any other"],
    certifications: ["freeCodeCamp certifications", "Meta Front-End Developer Certificate"],
    beginnerProjects: ["Build a simple to-do list app", "Recreate a page from a real website using code you wrote yourself"],
    portfolioRequirements: ["A public code repository with 2-3 working projects", "Clear README explaining what each project does"],
    remoteSuitable: true,
    freelanceSuitable: true,
    environments: ["REMOTE", "HYBRID", "IN_PERSON"],
    skills: [
      { name: "Programming fundamentals", level: "INTERMEDIATE" },
      { name: "JavaScript", level: "INTERMEDIATE" },
      { name: "Basic HTML/CSS", level: "INTERMEDIATE" },
      { name: "Database basics", level: "BEGINNER" },
      { name: "Problem solving", level: "ADVANCED" },
    ],
  },
  {
    slug: "web-development",
    name: "Web Development",
    description: "Designing and building websites — from a small business page to a full online store.",
    industry: "Technology",
    responsibilities: [
      "Turn a design into a working website",
      "Make sites work well on phones and slow connections",
      "Fix layout and functionality issues",
      "Maintain and update existing sites",
    ],
    relevantSubjects: ["Mathematics", "Computer Science", "Art"],
    relevantInterests: ["Technology & software", "Design & visual arts"],
    traitWeights: { analyticalThinking: 0.7, technologyInterest: 0.9, creativity: 0.6, problemSolving: 0.7 },
    educationPathways: ["Computer Science or IT-related degree"],
    alternativePathways: ["Self-taught via free web development courses and real client projects"],
    certifications: ["freeCodeCamp Responsive Web Design Certificate"],
    beginnerProjects: ["Build a one-page website for a local business or organization", "Rebuild a landing page from a screenshot"],
    portfolioRequirements: ["2-3 live or locally-built websites", "Mobile-responsive examples"],
    remoteSuitable: true,
    freelanceSuitable: true,
    environments: ["REMOTE", "HYBRID"],
    skills: [
      { name: "Basic HTML/CSS", level: "INTERMEDIATE" },
      { name: "JavaScript", level: "BEGINNER" },
      { name: "Programming fundamentals", level: "BEGINNER" },
      { name: "Wireframing & prototyping", level: "BEGINNER" },
    ],
  },
  {
    slug: "data-analysis",
    name: "Data Analysis",
    description: "Turning raw numbers into insights that help an organization make better decisions.",
    industry: "Technology & Business",
    responsibilities: [
      "Clean and organize data",
      "Build spreadsheets, dashboards, or reports",
      "Spot patterns and explain what they mean",
      "Present findings clearly to non-technical people",
    ],
    relevantSubjects: ["Mathematics", "Economics", "Statistics", "Computer Science"],
    relevantInterests: ["Technology & software", "Science & research", "Finance & investing"],
    traitWeights: { analyticalThinking: 0.9, problemSolving: 0.7, communication: 0.5, technologyInterest: 0.6 },
    educationPathways: ["Statistics, Economics, Mathematics, or Computer Science degree"],
    alternativePathways: ["Self-taught via free data analytics courses plus real spreadsheet/dashboard projects"],
    certifications: ["Google Data Analytics Certificate"],
    beginnerProjects: ["Analyze a public dataset and summarize 3 findings in a short report", "Build a spreadsheet dashboard tracking a real or sample budget"],
    portfolioRequirements: ["2-3 analysis write-ups with charts", "A short explanation of the question each analysis answered"],
    remoteSuitable: true,
    freelanceSuitable: true,
    environments: ["REMOTE", "HYBRID", "IN_PERSON"],
    skills: [
      { name: "Spreadsheets & data entry", level: "ADVANCED" },
      { name: "Data analysis basics", level: "INTERMEDIATE" },
      { name: "Analytics & reporting", level: "INTERMEDIATE" },
      { name: "Critical thinking", level: "INTERMEDIATE" },
      { name: "Database basics", level: "BEGINNER" },
    ],
  },
  {
    slug: "ux-ui-design",
    name: "UX/UI Design",
    description: "Designing how apps and websites look and feel, so they're easy and pleasant to use.",
    industry: "Technology & Design",
    responsibilities: [
      "Research how people use a product",
      "Sketch and prototype screens and flows",
      "Test designs with real users",
      "Work closely with developers to bring designs to life",
    ],
    relevantSubjects: ["Art", "Computer Science", "Psychology"],
    relevantInterests: ["Design & visual arts", "Technology & software"],
    traitWeights: { creativity: 0.8, analyticalThinking: 0.5, socialOrientation: 0.5, technologyInterest: 0.6 },
    educationPathways: ["Design, HCI, or Computer Science degree"],
    alternativePathways: ["Self-taught via free UX courses and case-study projects"],
    certifications: ["Google UX Design Certificate"],
    beginnerProjects: ["Redesign a screen from an app you use often and explain your reasoning", "Run a 5-person usability test on a simple prototype"],
    portfolioRequirements: ["2-3 case studies showing your design process, not just final screens"],
    remoteSuitable: true,
    freelanceSuitable: true,
    environments: ["REMOTE", "HYBRID"],
    skills: [
      { name: "Wireframing & prototyping", level: "INTERMEDIATE" },
      { name: "UX research", level: "BEGINNER" },
      { name: "Illustration / drawing", level: "BEGINNER" },
      { name: "Canva / basic graphic design", level: "INTERMEDIATE" },
    ],
  },
  {
    slug: "it-support",
    name: "IT Support & Systems Administration",
    description: "Keeping computers, networks, and everyday tech running for an organization or its clients.",
    industry: "Technology",
    responsibilities: [
      "Troubleshoot hardware and software problems",
      "Set up and maintain computers and networks",
      "Support staff with day-to-day tech issues",
      "Keep systems secure and backed up",
    ],
    relevantSubjects: ["Computer Science", "Physics", "Mathematics"],
    relevantInterests: ["Technology & software", "Engineering & how things work"],
    traitWeights: { problemSolving: 0.8, technologyInterest: 0.9, structurePreference: 0.5 },
    educationPathways: ["IT or Computer Science diploma/degree"],
    alternativePathways: ["Certificate-based entry — this field hires heavily on certification plus hands-on troubleshooting ability"],
    certifications: ["CompTIA A+", "Google IT Support Certificate", "CompTIA Network+"],
    beginnerProjects: ["Set up and document a small home network", "Diagnose and write up fixes for 5 common computer problems"],
    portfolioRequirements: ["A troubleshooting log or documented case studies of problems you've solved"],
    remoteSuitable: false,
    freelanceSuitable: true,
    environments: ["IN_PERSON", "HYBRID"],
    skills: [
      { name: "Network & hardware troubleshooting", level: "INTERMEDIATE" },
      { name: "Basic computer literacy", level: "ADVANCED" },
      { name: "Problem solving", level: "INTERMEDIATE" },
      { name: "Customer communication", level: "BEGINNER" },
    ],
  },
  {
    slug: "content-writing",
    name: "Content Writing & Journalism",
    description: "Writing articles, blog posts, scripts, or reports that inform or engage an audience.",
    industry: "Media & Communications",
    responsibilities: [
      "Research topics and interview sources",
      "Write clear, engaging articles or scripts",
      "Edit and proofread your own and others' work",
      "Adapt tone and style for different audiences",
    ],
    relevantSubjects: ["English", "Literature", "History", "Journalism"],
    relevantInterests: ["Writing & storytelling", "Media & journalism"],
    traitWeights: { communication: 0.9, creativity: 0.7, analyticalThinking: 0.4, socialOrientation: 0.4 },
    educationPathways: ["English, Journalism, or Communications degree"],
    alternativePathways: ["Self-taught with a strong published writing portfolio — clips matter more than the degree"],
    certifications: ["HubSpot Content Marketing Certification"],
    beginnerProjects: ["Write 3 articles on topics you know well", "Interview someone and write a short profile piece"],
    portfolioRequirements: ["3-5 writing samples across different formats", "Links to any published work, even on a personal blog"],
    remoteSuitable: true,
    freelanceSuitable: true,
    environments: ["REMOTE", "HYBRID"],
    skills: [
      { name: "Written English", level: "ADVANCED" },
      { name: "Storytelling", level: "INTERMEDIATE" },
      { name: "Research skills", level: "INTERMEDIATE" },
      { name: "Content strategy", level: "BEGINNER" },
    ],
  },
  {
    slug: "graphic-design",
    name: "Graphic Design",
    description: "Creating visual content — logos, posters, social posts, packaging — that communicates a message.",
    industry: "Creative & Design",
    responsibilities: [
      "Design visuals to a brief",
      "Choose colors, type, and layout that fit a brand",
      "Revise work based on feedback",
      "Prepare files for print or digital use",
    ],
    relevantSubjects: ["Art", "Design", "Computer Science"],
    relevantInterests: ["Design & visual arts", "Marketing & branding"],
    traitWeights: { creativity: 0.9, communication: 0.4, technologyInterest: 0.4 },
    educationPathways: ["Graphic Design or Fine Art degree"],
    alternativePathways: ["Self-taught with strong design tool skills and a public portfolio"],
    certifications: ["Canva Design certifications (free)"],
    beginnerProjects: ["Design a full brand kit (logo, colors, fonts) for a fictional business", "Redesign a poster or flyer you've seen and improve it"],
    portfolioRequirements: ["6-10 varied design pieces", "At least one full project shown start to finish"],
    remoteSuitable: true,
    freelanceSuitable: true,
    environments: ["REMOTE", "HYBRID", "IN_PERSON"],
    skills: [
      { name: "Canva / basic graphic design", level: "ADVANCED" },
      { name: "Illustration / drawing", level: "INTERMEDIATE" },
      { name: "Content creation", level: "INTERMEDIATE" },
    ],
  },
  {
    slug: "video-editing-production",
    name: "Video Editing & Production",
    description: "Shooting and editing video — social content, interviews, promos, or short films.",
    industry: "Creative & Media",
    responsibilities: [
      "Plan and shoot video content",
      "Edit footage into a finished piece",
      "Add sound, captions, and graphics",
      "Deliver content in the right format for the platform",
    ],
    relevantSubjects: ["Art", "Media Studies", "Computer Science"],
    relevantInterests: ["Design & visual arts", "Media & journalism", "Music & performance"],
    traitWeights: { creativity: 0.9, technologyInterest: 0.5, practicalPreference: 0.4 },
    educationPathways: ["Film, Media Production, or related degree"],
    alternativePathways: ["Self-taught with a smartphone and free editing software — this field rewards a strong reel over credentials"],
    certifications: ["Platform-specific free tutorials (no formal certificate required to start)"],
    beginnerProjects: ["Shoot and edit a 60-second promo for a local business or event", "Edit a highlight reel from existing footage"],
    portfolioRequirements: ["A 2-3 minute reel showcasing your best edits"],
    remoteSuitable: true,
    freelanceSuitable: true,
    environments: ["REMOTE", "HYBRID", "IN_PERSON"],
    skills: [
      { name: "Video editing basics", level: "INTERMEDIATE" },
      { name: "Advanced video production", level: "BEGINNER" },
      { name: "Storytelling", level: "INTERMEDIATE" },
      { name: "Photography", level: "BEGINNER" },
    ],
  },
  {
    slug: "public-relations",
    name: "Public Relations & Communications",
    description: "Managing how an organization communicates with the public, media, and its own community.",
    industry: "Marketing & Communications",
    responsibilities: [
      "Write press releases and public statements",
      "Build relationships with journalists and media",
      "Manage an organization's public image",
      "Prepare spokespeople for interviews",
    ],
    relevantSubjects: ["English", "Communications", "History", "Political Science"],
    relevantInterests: ["Media & journalism", "Business & entrepreneurship", "Law & policy"],
    traitWeights: { communication: 0.9, leadership: 0.5, socialOrientation: 0.5, businessOrientation: 0.4 },
    educationPathways: ["Communications, Journalism, or Public Relations degree"],
    alternativePathways: ["Communications experience from student organizations, NGOs, or volunteering, plus a writing portfolio"],
    certifications: ["HubSpot Content Marketing Certification"],
    beginnerProjects: ["Write a press release for a fictional product launch", "Draft a crisis-communication statement for a hypothetical scenario"],
    portfolioRequirements: ["3-5 writing samples (press releases, statements, pitches)"],
    remoteSuitable: true,
    freelanceSuitable: false,
    environments: ["HYBRID", "IN_PERSON", "REMOTE"],
    skills: [
      { name: "Public speaking", level: "INTERMEDIATE" },
      { name: "Press release writing", level: "BEGINNER" },
      { name: "Media relations", level: "BEGINNER" },
      { name: "Written English", level: "INTERMEDIATE" },
    ],
  },
  {
    slug: "translation-localization",
    name: "Translation & Localization",
    description: "Converting written or spoken content accurately from one language to another.",
    industry: "Media & Communications",
    responsibilities: [
      "Translate documents, subtitles, or websites",
      "Preserve tone and meaning across languages",
      "Proofread and quality-check translated work",
      "Research terminology for specialized topics",
    ],
    relevantSubjects: ["English", "French", "Literature", "Languages"],
    relevantInterests: ["Writing & storytelling", "Travel & culture"],
    traitWeights: { communication: 0.8, analyticalThinking: 0.4, structurePreference: 0.4 },
    educationPathways: ["Languages, Translation, or Linguistics degree"],
    alternativePathways: ["Fluency plus a certification and a track record of accurate sample translations"],
    certifications: ["Language proficiency certificates (e.g. DELF/DALF for French, IELTS/TOEFL for English)"],
    beginnerProjects: ["Translate a short article or document and have a fluent speaker review it", "Subtitle a short video"],
    portfolioRequirements: ["2-3 sample translations across different content types"],
    remoteSuitable: true,
    freelanceSuitable: true,
    environments: ["REMOTE"],
    skills: [
      { name: "Translation", level: "ADVANCED" },
      { name: "Written English", level: "ADVANCED" },
      { name: "Written French", level: "ADVANCED" },
      { name: "Research skills", level: "BEGINNER" },
    ],
  },
  {
    slug: "photography",
    name: "Photography",
    description: "Capturing images for events, portraits, products, or stories.",
    industry: "Creative & Media",
    responsibilities: [
      "Plan and shoot photos for a client or project",
      "Edit and retouch images",
      "Manage equipment and shoot logistics",
      "Deliver final images on time",
    ],
    relevantSubjects: ["Art", "Media Studies"],
    relevantInterests: ["Design & visual arts", "Travel & culture"],
    traitWeights: { creativity: 0.9, practicalPreference: 0.5, socialOrientation: 0.3 },
    educationPathways: ["No formal degree required — skill and portfolio matter most"],
    alternativePathways: ["Self-taught with a smartphone or entry-level camera and consistent practice"],
    certifications: ["No formal certificate expected — a strong portfolio substitutes"],
    beginnerProjects: ["Shoot and edit a themed photo series (10 images)", "Offer a free or low-cost shoot to build initial portfolio pieces"],
    portfolioRequirements: ["10-15 of your best images across a few categories (portraits, events, products)"],
    remoteSuitable: false,
    freelanceSuitable: true,
    environments: ["IN_PERSON"],
    skills: [
      { name: "Photography", level: "INTERMEDIATE" },
      { name: "Canva / basic graphic design", level: "BEGINNER" },
      { name: "Client relationship management", level: "BEGINNER" },
    ],
  },
  {
    slug: "sales-business-development",
    name: "Sales & Business Development",
    description: "Finding and winning customers or partners for a business, and growing existing relationships.",
    industry: "Business",
    responsibilities: [
      "Reach out to potential customers or partners",
      "Understand customer needs and pitch solutions",
      "Negotiate deals and close sales",
      "Track and follow up on leads",
    ],
    relevantSubjects: ["Business Studies", "Economics", "English"],
    relevantInterests: ["Business & entrepreneurship", "Marketing & branding"],
    traitWeights: { communication: 0.8, businessOrientation: 0.9, socialOrientation: 0.5, motivation: 0.6 },
    educationPathways: ["Business, Marketing, or any degree — this field values results and communication skill"],
    alternativePathways: ["Entry-level sales roles that train on the job, no degree required"],
    certifications: ["HubSpot Sales Certification"],
    beginnerProjects: ["Practice a 2-minute pitch for a product and record yourself", "Research and list 20 potential customers for a hypothetical product with a suggested approach for each"],
    portfolioRequirements: ["Examples of pitches or outreach messages you've written", "Any measurable results from real sales/outreach experience"],
    remoteSuitable: true,
    freelanceSuitable: true,
    environments: ["IN_PERSON", "HYBRID", "REMOTE"],
    skills: [
      { name: "Sales & negotiation", level: "INTERMEDIATE" },
      { name: "Customer communication", level: "INTERMEDIATE" },
      { name: "Client relationship management", level: "BEGINNER" },
    ],
  },
  {
    slug: "accounting-finance",
    name: "Accounting & Finance",
    description: "Managing financial records, budgets, and reporting for a business or organization.",
    industry: "Business & Finance",
    responsibilities: [
      "Record and reconcile financial transactions",
      "Prepare budgets and financial reports",
      "Ensure compliance with financial regulations",
      "Support financial decision-making with data",
    ],
    relevantSubjects: ["Mathematics", "Economics", "Accounting", "Business Studies"],
    relevantInterests: ["Finance & investing", "Business & entrepreneurship"],
    traitWeights: { analyticalThinking: 0.8, structurePreference: 0.7, businessOrientation: 0.5 },
    educationPathways: ["Accounting, Finance, or Economics degree"],
    alternativePathways: ["Accounting certificate/diploma programs, entry-level bookkeeping roles"],
    certifications: ["ACCA / local chartered accountancy pathways", "Basic bookkeeping certificates"],
    beginnerProjects: ["Build a full monthly budget and reconciliation for a small hypothetical business", "Prepare a simple income statement from sample transactions"],
    portfolioRequirements: ["Sample spreadsheets or reports demonstrating accuracy and structure"],
    remoteSuitable: true,
    freelanceSuitable: true,
    environments: ["IN_PERSON", "HYBRID", "REMOTE"],
    skills: [
      { name: "Basic bookkeeping", level: "INTERMEDIATE" },
      { name: "Financial analysis", level: "BEGINNER" },
      { name: "Spreadsheets & data entry", level: "ADVANCED" },
      { name: "Critical thinking", level: "INTERMEDIATE" },
    ],
  },
  {
    slug: "human-resources",
    name: "Human Resources",
    description: "Supporting an organization's people — hiring, onboarding, policies, and workplace culture.",
    industry: "Business",
    responsibilities: [
      "Coordinate recruitment and interviews",
      "Onboard new employees",
      "Support staff with workplace questions and policies",
      "Help build a healthy work culture",
    ],
    relevantSubjects: ["Business Studies", "Psychology", "English"],
    relevantInterests: ["Business & entrepreneurship", "Community & social impact"],
    traitWeights: { communication: 0.7, socialOrientation: 0.6, structurePreference: 0.5, leadership: 0.4 },
    educationPathways: ["Human Resources, Business, or Psychology degree"],
    alternativePathways: ["Administrative or coordination experience plus HR fundamentals training"],
    certifications: ["HR fundamentals certificate programs (e.g. via Coursera/edX)"],
    beginnerProjects: ["Write a full onboarding plan for a new hire at a fictional company", "Draft an employee handbook policy section"],
    portfolioRequirements: ["Sample HR documents (job descriptions, onboarding plans, policy drafts)"],
    remoteSuitable: false,
    freelanceSuitable: false,
    environments: ["IN_PERSON", "HYBRID"],
    skills: [
      { name: "Recruitment & interviewing", level: "BEGINNER" },
      { name: "Payroll & compliance basics", level: "BEGINNER" },
      { name: "Customer communication", level: "INTERMEDIATE" },
      { name: "Project coordination", level: "BEGINNER" },
    ],
  },
  {
    slug: "project-management",
    name: "Project Management",
    description: "Planning and coordinating the people, timeline, and budget needed to get a project done.",
    industry: "Business",
    responsibilities: [
      "Plan project timelines and milestones",
      "Coordinate a team toward a shared goal",
      "Track budget and resources",
      "Manage risks and unblock problems",
    ],
    relevantSubjects: ["Business Studies", "Mathematics"],
    relevantInterests: ["Business & entrepreneurship", "Engineering & how things work"],
    traitWeights: { leadership: 0.7, structurePreference: 0.7, communication: 0.6, analyticalThinking: 0.4 },
    educationPathways: ["Any degree, especially Business, Engineering, or IT"],
    alternativePathways: ["Coordination experience (events, student groups, volunteer projects) plus a project management certificate"],
    certifications: ["Google Project Management Certificate"],
    beginnerProjects: ["Plan a full project timeline and budget for a real or hypothetical event", "Run a small project from start to finish and document the process"],
    portfolioRequirements: ["A documented project plan showing timeline, budget, and risk considerations"],
    remoteSuitable: true,
    freelanceSuitable: true,
    environments: ["HYBRID", "IN_PERSON", "REMOTE"],
    skills: [
      { name: "Project coordination", level: "INTERMEDIATE" },
      { name: "Scheduling & planning", level: "INTERMEDIATE" },
      { name: "Budgeting", level: "BEGINNER" },
      { name: "Risk management", level: "BEGINNER" },
    ],
  },
  {
    slug: "entrepreneurship",
    name: "Entrepreneurship & Small Business Management",
    description: "Starting and running your own venture — identifying an opportunity and building a business around it.",
    industry: "Business",
    responsibilities: [
      "Identify and validate a business idea",
      "Manage day-to-day operations",
      "Handle basic finances and customers",
      "Adapt the business as you learn what works",
    ],
    relevantSubjects: ["Business Studies", "Economics", "Mathematics"],
    relevantInterests: ["Business & entrepreneurship", "Marketing & branding"],
    traitWeights: { businessOrientation: 0.9, motivation: 0.8, problemSolving: 0.6, leadership: 0.5 },
    educationPathways: ["Any background — this path is defined by the venture, not a specific degree"],
    alternativePathways: ["Starting small (a side venture) while building skills and capital"],
    certifications: ["No formal certificate required — business plan competitions and incubator programs are useful proof points"],
    beginnerProjects: ["Write a one-page business plan for a real idea", "Run a small pilot sale or service and document what you learned"],
    portfolioRequirements: ["A business plan or pitch deck, and evidence of any real traction (even small)"],
    remoteSuitable: true,
    freelanceSuitable: true,
    environments: ["NO_PREFERENCE", "IN_PERSON", "HYBRID", "REMOTE"],
    skills: [
      { name: "Business plan development", level: "BEGINNER" },
      { name: "Sales & negotiation", level: "BEGINNER" },
      { name: "Basic bookkeeping", level: "BEGINNER" },
      { name: "Pitching & fundraising basics", level: "BEGINNER" },
    ],
  },
  {
    slug: "teaching-tutoring",
    name: "Teaching & Tutoring",
    description: "Helping others learn — in a classroom, online, or one-on-one.",
    industry: "Education",
    responsibilities: [
      "Plan lessons and explain concepts clearly",
      "Assess understanding and adjust your approach",
      "Manage a classroom or tutoring session",
      "Encourage and motivate learners",
    ],
    relevantSubjects: ["Any subject you're strong in", "Education", "Psychology"],
    relevantInterests: ["Teaching & mentoring", "Community & social impact"],
    traitWeights: { communication: 0.8, socialOrientation: 0.7, leadership: 0.5, structurePreference: 0.4 },
    educationPathways: ["Education degree for formal teaching roles"],
    alternativePathways: ["Subject expertise plus tutoring experience — a formal teaching credential isn't required for private tutoring"],
    certifications: ["Subject-specific or teaching-methodology certificates (varies by context)"],
    beginnerProjects: ["Prepare and deliver a 20-minute lesson on a topic you know well to a friend or family member", "Create a simple lesson plan and practice worksheet"],
    portfolioRequirements: ["Sample lesson plans", "Any feedback from students or people you've tutored"],
    remoteSuitable: true,
    freelanceSuitable: true,
    environments: ["IN_PERSON", "REMOTE", "HYBRID"],
    skills: [
      { name: "Teaching / tutoring", level: "INTERMEDIATE" },
      { name: "Lesson planning", level: "BEGINNER" },
      { name: "Classroom & behavior management", level: "BEGINNER" },
      { name: "Public speaking", level: "BEGINNER" },
    ],
  },
  {
    slug: "nursing-community-health",
    name: "Nursing & Community Health",
    description: "Providing direct care and health education to patients and communities.",
    industry: "Health",
    responsibilities: [
      "Provide basic patient care and monitoring",
      "Educate patients and communities on health practices",
      "Support health workers and clinics",
      "Follow health and safety protocols",
    ],
    relevantSubjects: ["Biology", "Chemistry", "Health Science"],
    relevantInterests: ["Health & medicine", "Community & social impact"],
    traitWeights: { socialOrientation: 0.9, communication: 0.5, structurePreference: 0.5, motivation: 0.5 },
    educationPathways: ["Nursing diploma or degree, health sciences program"],
    alternativePathways: ["Community health worker training programs (shorter, still credentialed)"],
    certifications: ["Nursing council licensure (required to practice)", "First aid / basic life support certification"],
    beginnerProjects: ["Volunteer or shadow at a local clinic or health outreach event", "Create a health education flyer on a topic like hygiene or nutrition"],
    portfolioRequirements: ["Volunteer or clinical placement records", "Evidence of required licensure once qualified"],
    remoteSuitable: false,
    freelanceSuitable: false,
    environments: ["IN_PERSON"],
    skills: [
      { name: "Patient care basics", level: "BEGINNER" },
      { name: "Health & hygiene education", level: "BEGINNER" },
      { name: "Customer communication", level: "INTERMEDIATE" },
    ],
  },
  {
    slug: "social-work-community-development",
    name: "Social Work & Community Development",
    description: "Supporting individuals and communities to address social, economic, or wellbeing challenges.",
    industry: "Social Impact",
    responsibilities: [
      "Work directly with individuals or community groups",
      "Connect people with resources and support",
      "Run or support community programs",
      "Document cases and track outcomes",
    ],
    relevantSubjects: ["Sociology", "Psychology", "Social Studies"],
    relevantInterests: ["Community & social impact", "Teaching & mentoring"],
    traitWeights: { socialOrientation: 0.9, communication: 0.6, motivation: 0.5 },
    educationPathways: ["Social Work, Sociology, or Development Studies degree"],
    alternativePathways: ["Volunteer and NGO experience combined with community-development training"],
    certifications: ["Program-specific NGO/community-development training (varies by organization)"],
    beginnerProjects: ["Volunteer with a local community organization and document your work", "Design a small community awareness campaign on a local issue"],
    portfolioRequirements: ["Documented volunteer or program experience", "Any community initiatives you've contributed to or led"],
    remoteSuitable: false,
    freelanceSuitable: false,
    environments: ["IN_PERSON"],
    skills: [
      { name: "Community outreach", level: "BEGINNER" },
      { name: "Case management basics", level: "BEGINNER" },
      { name: "Customer communication", level: "INTERMEDIATE" },
    ],
  },
  {
    slug: "customer-support",
    name: "Customer Support",
    description: "Helping customers solve problems and have a good experience with a product or service.",
    industry: "Business & Technology",
    responsibilities: [
      "Respond to customer questions and issues",
      "Troubleshoot problems or escalate when needed",
      "Keep records of customer interactions",
      "Represent the brand in every interaction",
    ],
    relevantSubjects: ["English", "Business Studies"],
    relevantInterests: ["Business & entrepreneurship", "Community & social impact"],
    traitWeights: { communication: 0.8, socialOrientation: 0.6, structurePreference: 0.4 },
    educationPathways: ["No specific degree required"],
    alternativePathways: ["Entry-level remote customer support roles — one of the most accessible remote starting points"],
    certifications: ["No formal certificate expected"],
    beginnerProjects: ["Write sample responses to 5 common customer complaints", "Practice a mock support call or chat script"],
    portfolioRequirements: ["Sample written responses demonstrating tone and problem-solving"],
    remoteSuitable: true,
    freelanceSuitable: true,
    environments: ["REMOTE", "IN_PERSON", "HYBRID"],
    skills: [
      { name: "Customer communication", level: "INTERMEDIATE" },
      { name: "Written English", level: "INTERMEDIATE" },
      { name: "Problem solving", level: "BEGINNER" },
      { name: "Calendar & email management", level: "BEGINNER" },
    ],
  },
  {
    slug: "agribusiness-agronomy",
    name: "Agribusiness & Agronomy",
    description: "Applying science and business thinking to farming — growing crops or livestock and running it as a business.",
    industry: "Agriculture",
    responsibilities: [
      "Plan and manage crop or livestock production",
      "Apply soil, water, and pest management practices",
      "Manage costs and sell produce profitably",
      "Adopt new techniques to improve yield",
    ],
    relevantSubjects: ["Biology", "Chemistry", "Agricultural Science", "Business Studies"],
    relevantInterests: ["Environment & agriculture", "Business & entrepreneurship", "Science & research"],
    traitWeights: { practicalPreference: 0.8, businessOrientation: 0.5, analyticalThinking: 0.4, motivation: 0.5 },
    educationPathways: ["Agricultural Science, Agribusiness, or Agronomy degree"],
    alternativePathways: ["Hands-on farming experience plus agribusiness training programs"],
    certifications: ["Agricultural extension / agribusiness training certificates (often via local ministries or NGOs)"],
    beginnerProjects: ["Plan a small crop or garden project including budget and expected yield", "Document a soil or pest-management improvement you tested"],
    portfolioRequirements: ["Photos and notes documenting any real growing project you've run"],
    remoteSuitable: false,
    freelanceSuitable: true,
    environments: ["IN_PERSON"],
    skills: [
      { name: "Crop & soil management", level: "BEGINNER" },
      { name: "Farm business planning", level: "BEGINNER" },
      { name: "Basic bookkeeping", level: "BEGINNER" },
    ],
  },
  {
    slug: "civil-engineering",
    name: "Civil Engineering",
    description: "Designing and overseeing construction of buildings, roads, and other infrastructure.",
    industry: "Engineering & Construction",
    responsibilities: [
      "Draft and review technical designs",
      "Supervise construction sites",
      "Ensure structures meet safety standards",
      "Coordinate with contractors and clients",
    ],
    relevantSubjects: ["Mathematics", "Physics", "Technical Drawing"],
    relevantInterests: ["Engineering & how things work", "Building & fixing things"],
    traitWeights: { analyticalThinking: 0.8, practicalPreference: 0.6, structurePreference: 0.6, leadership: 0.4 },
    educationPathways: ["Civil Engineering degree (required for licensure)"],
    alternativePathways: ["Technician-level entry via a diploma, working under a licensed engineer"],
    certifications: ["Professional engineering licensure (required to practice independently)"],
    beginnerProjects: ["Produce a basic technical drawing of a small structure", "Document a site visit with observations on construction quality"],
    portfolioRequirements: ["Technical drawings or site documentation from coursework or internships"],
    remoteSuitable: false,
    freelanceSuitable: false,
    environments: ["IN_PERSON"],
    skills: [
      { name: "Technical drawing / CAD basics", level: "BEGINNER" },
      { name: "Construction site supervision", level: "BEGINNER" },
      { name: "Critical thinking", level: "INTERMEDIATE" },
    ],
  },
  {
    slug: "electrical-renewable-energy",
    name: "Electrical & Renewable Energy Technician",
    description: "Installing and maintaining electrical systems, including growing work in solar and renewable energy.",
    industry: "Engineering & Energy",
    responsibilities: [
      "Install and repair electrical wiring and systems",
      "Install and maintain solar panel systems",
      "Follow safety codes and standards",
      "Diagnose and fix electrical faults",
    ],
    relevantSubjects: ["Physics", "Mathematics", "Technical Drawing"],
    relevantInterests: ["Engineering & how things work", "Building & fixing things", "Environment & agriculture"],
    traitWeights: { practicalPreference: 0.9, problemSolving: 0.6, structurePreference: 0.5 },
    educationPathways: ["Electrical engineering or technical/vocational diploma"],
    alternativePathways: ["Apprenticeship under a licensed electrician plus a safety certification"],
    certifications: ["Electrical trade licensure/certification (required in most contexts)", "Solar installation training certificates"],
    beginnerProjects: ["Document a basic home wiring safety inspection", "Build and explain a simple solar-powered charging setup"],
    portfolioRequirements: ["Photos and notes from any hands-on electrical or solar work, supervised or personal"],
    remoteSuitable: false,
    freelanceSuitable: true,
    environments: ["IN_PERSON"],
    skills: [
      { name: "Electrical wiring & safety", level: "BEGINNER" },
      { name: "Solar & renewable installation basics", level: "BEGINNER" },
      { name: "Problem solving", level: "INTERMEDIATE" },
    ],
  },
];

// Sensible cross-links between related careers (bidirectional).
const RELATED_PAIRS: [string, string][] = [
  ["digital-marketing", "public-relations"],
  ["digital-marketing", "sales-business-development"],
  ["digital-marketing", "content-writing"],
  ["software-development", "web-development"],
  ["software-development", "data-analysis"],
  ["software-development", "it-support"],
  ["web-development", "ux-ui-design"],
  ["ux-ui-design", "graphic-design"],
  ["graphic-design", "video-editing-production"],
  ["content-writing", "public-relations"],
  ["content-writing", "translation-localization"],
  ["accounting-finance", "sales-business-development"],
  ["accounting-finance", "entrepreneurship"],
  ["human-resources", "project-management"],
  ["project-management", "entrepreneurship"],
  ["teaching-tutoring", "social-work-community-development"],
  ["nursing-community-health", "social-work-community-development"],
  ["civil-engineering", "electrical-renewable-energy"],
  ["customer-support", "sales-business-development"],
  ["data-analysis", "accounting-finance"],
];

async function main() {
  for (const skill of CAREER_SKILLS) {
    await prisma.skill.upsert({
      where: { name: skill.name },
      update: { category: skill.category },
      create: skill,
    });
  }

  for (const career of CAREERS) {
    const record = await prisma.careerProfile.upsert({
      where: { slug: career.slug },
      update: {
        name: career.name,
        description: career.description,
        industry: career.industry,
        responsibilities: career.responsibilities,
        relevantSubjects: career.relevantSubjects,
        relevantInterests: career.relevantInterests,
        traitWeights: career.traitWeights,
        educationPathways: career.educationPathways,
        alternativePathways: career.alternativePathways,
        certifications: career.certifications,
        beginnerProjects: career.beginnerProjects,
        portfolioRequirements: career.portfolioRequirements,
        remoteSuitable: career.remoteSuitable,
        freelanceSuitable: career.freelanceSuitable,
        environments: career.environments,
      },
      create: {
        slug: career.slug,
        name: career.name,
        description: career.description,
        industry: career.industry,
        responsibilities: career.responsibilities,
        relevantSubjects: career.relevantSubjects,
        relevantInterests: career.relevantInterests,
        traitWeights: career.traitWeights,
        educationPathways: career.educationPathways,
        alternativePathways: career.alternativePathways,
        certifications: career.certifications,
        beginnerProjects: career.beginnerProjects,
        portfolioRequirements: career.portfolioRequirements,
        remoteSuitable: career.remoteSuitable,
        freelanceSuitable: career.freelanceSuitable,
        environments: career.environments,
      },
    });

    for (const skill of career.skills) {
      const skillRow = await prisma.skill.findUnique({ where: { name: skill.name } });
      if (!skillRow) throw new Error(`Unknown skill "${skill.name}" referenced by career "${career.slug}"`);
      await prisma.careerSkill.upsert({
        where: { careerId_skillId: { careerId: record.id, skillId: skillRow.id } },
        update: { level: skill.level },
        create: { careerId: record.id, skillId: skillRow.id, level: skill.level },
      });
    }
  }

  for (const [slugA, slugB] of RELATED_PAIRS) {
    const [a, b] = await Promise.all([
      prisma.careerProfile.findUniqueOrThrow({ where: { slug: slugA } }),
      prisma.careerProfile.findUniqueOrThrow({ where: { slug: slugB } }),
    ]);
    await prisma.careerProfile.update({
      where: { id: a.id },
      data: { relatedCareers: { connect: { id: b.id } } },
    });
    await prisma.careerProfile.update({
      where: { id: b.id },
      data: { relatedCareers: { connect: { id: a.id } } },
    });
  }

  console.log(`Seeded ${CAREERS.length} careers, ${CAREER_SKILLS.length} additional skills, ${RELATED_PAIRS.length} related-career links.`);
}

main()
  .catch((err) => {
    console.error(err);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
