import type { Metadata } from "next";
import { Logo } from "@/components/logo";

export const metadata: Metadata = { title: "Privacy" };

export default function PrivacyPage() {
  return (
    <div className="min-h-dvh bg-sand-50">
      <header className="px-6 py-6 sm:px-10">
        <Logo />
      </header>
      <main className="mx-auto max-w-2xl px-6 pb-24">
        <h1 className="text-3xl font-bold text-ink">Privacy</h1>
        <p className="mt-2 text-sm text-ink-faint">Last updated August 2026</p>

        <div className="prose-p:text-ink-soft mt-8 space-y-6 text-[15px] leading-relaxed text-ink-soft">
          <p>
            3Doors asks for personal information to make its career guidance specific to you
            rather than generic. This page explains what we collect and why, in plain language.
          </p>

          <section>
            <h2 className="font-display text-lg font-semibold text-ink">What we collect</h2>
            <p className="mt-2">
              Only what improves the guidance you receive: your account details, education and
              subjects, self-reported skills and interests, your goals and availability, device
              and internet access, and your answers to the self-discovery assessment. We do not
              ask for information we don&apos;t use.
            </p>
          </section>

          <section>
            <h2 className="font-display text-lg font-semibold text-ink">How AI guidance works</h2>
            <p className="mt-2">
              Career matches, skill gaps, and roadmaps are generated by an AI system reasoning
              over your profile and a curated career knowledge base. This is career guidance, not
              a professional psychological, medical, or legal assessment. Recommendations are
              always labeled, and we never invent jobs, scholarships, companies, or salary
              figures — anything we can&apos;t verify, we say so.
            </p>
          </section>

          <section>
            <h2 className="font-display text-lg font-semibold text-ink">Users under 18</h2>
            <p className="mt-2">
              If you tell us you&apos;re under 18, your account defaults to the minimum
              information we need, we don&apos;t use your data for marketing, and language across
              the product is written for a younger reader.
            </p>
          </section>

          <section>
            <h2 className="font-display text-lg font-semibold text-ink">Your control over your data</h2>
            <p className="mt-2">
              You can edit your profile at any time. You can delete your account from your
              profile settings — this permanently removes your personal data; only anonymized,
              aggregate counts are retained for product analytics.
            </p>
          </section>

          <section>
            <h2 className="font-display text-lg font-semibold text-ink">Security</h2>
            <p className="mt-2">
              Passwords are hashed, never stored in plain text. All traffic is encrypted in
              transit. We do not sell your personal data.
            </p>
          </section>
        </div>
      </main>
    </div>
  );
}
